version: "3"

services:
    rabbitmq:
        image: rabbitmq:3.11-management
        container_name: RabbitMQ-1
        hostname: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password
        ports:
            - 5672:5672
            - 15672:15672
        restart: always
        networks:
            - docker_network
    
    mongodb:
        image: mongo:latest
        container_name: MongoDB-1
        ports:
            - 27017:27017
        volumes:
            - ./mongo:/data/db
        restart: always
        networks:
            - docker_network

    bot:
        build: /Users/mx4al/ООП/bot
        container_name: bot-1
        command: python ./bot.py
        env_file:
            - .env
        environment:
            BOT_TOKEN: ${TOKEN}
            RABBITMQ_URL: 'amqp://user:password@rabbitmq:5672'
            MONGO_HOST: mongodb
            MONGO_PORT: 27017
        depends_on:
            - rabbitmq
            - mongodb
        restart: on-failure:5
        networks:
            - docker_network

    server:
        build: /Users/mx4al/ООП/generation
        container_name: generation-1
        command: python ./gen_toast.py
        environment:
            RABBITMQ_URL: 'amqp://user:password@rabbitmq:5672'
        depends_on:
            - rabbitmq
            - bot
        restart: on-failure:5
        networks:
            - docker_network
            
networks:
    docker_network:
        driver: bridge

